repos:
  # Standard out-of-the-box pre-commit hooks
  - repo: https://github.com
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer

  # Ruff for linting and formatting
  - repo: https://github.com
    rev: v0.6.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # UV specific hooks to maintain lockfiles
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.3
    hooks:
      # Ensures uv.lock is up-to-date with pyproject.toml
      - id: uv-lock
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      -   id: reorder-python-imports
          exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
          args: [--py39-plus, --add-import, 'from __future__ import annotations']
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      -  id: add-trailing-comma
